name: Build SignalF - Release

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.12.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies SignalF.Controller
      run: dotnet restore ./Source/SignalF.Controller.sln
    - name: Build SignalF.Controller
      run: dotnet build --no-restore ./Source/SignalF.Controller.sln -c Release -p:Version=$GITVERSION_ASSEMBLYSEMVER -p:InformationalVersion=$GITVERSION_SEMVER -p:PackageVersion=$GITVERSION_SEMVER -p:CompanyName="scotec Software Solutions AB"
    - name: Restore dependencies SignalF.Controller.SourceGenerator
      run: dotnet restore ./Source/SignalF.Controller.SourceGenerator.sln
    - name: Build SignalF.Controller.SourceGenerator
      run: dotnet build --no-restore ./Source/SignalF.Controller.SourceGenerator.sln -c Release -p:Version=$GITVERSION_ASSEMBLYSEMVER -p:InformationalVersion=$GITVERSION_SEMVER -p:PackageVersion=$GITVERSION_SEMVER -p:CompanyName="scotec Software Solutions AB"
#    - name: Test
#      run: dotnet test --no-restore --no-build --verbosity normal ./Source/SignalF.Controller.sln
    - name: Push project
      run: dotnet nuget push LocalPackages/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate